---
- name: Install Docker on Ubuntu
  hosts: all
  remote_user: debian
  become: true

  tasks:
    - name: Add aliases
      ansible.builtin.blockinfile:
        path: /etc/bash.bashrc
        block: |
          alias d='docker'
          alias dc='docker compose'

    - name: Create file
      copy:
        dest: /etc/topsecret.txt
        content: |
          t0ps3cr3t

    - name: Set permissions
      ansible.builtin.file:
        path: /etc/topsecret.txt
        owner: root
        mode: 0600


