name: Build HelloWorld

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
              - name: Checkout
                uses: actions/checkout@v4.1.1
                with:
                  sparse-checkout: helloworld
              - name: Setup Java JDK
                uses: actions/setup-java@v4.1.0
                with:
                  distribution: 'temurin'
                  java-version: '21'
              - run: |
                  cd helloworld
                  ./gradlew build --no-daemon
